version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: isjQsxy9CSIhc5ysU6
      MONGO_INITDB_DATABASE: rendez
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
